language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO=1.4.2
  - DJANGO=1.5.1
  - DJANGO=1.6.0
matrix:
  exclude:
  - python: "3.2"
    env: DJANGO=1.4.2
  - python: "3.3"
    env: DJANGO=1.4.2
  - python: "3.4"
    env: DJANGO=1.4.2

install:
  - pip install -q coveralls  # installs coverage
  - pip install -q Django==$DJANGO
  - pip install -q -e .

script:
  - coverage run --source=example/article,parler runtests.py

after_success:
  - coveralls --verbose

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - travis@edoburu.nl
    on_success: never
    on_failure: always
